Initial setup for the calculator
Postreen/credit-bank pull request #1
Opened 2024-11-24 18:36 UTC by Postreen

Add Spring-Boot calculator application

2024-11-27 13:26 UTC, Ononan commented on Calculator/app.log
В репозитории должны присутствовать только исходный код проекта и артефакты для его запуска, результат его работы коммитить не нужно(требуется добавить в .gitignore) как в данном случае логи работы приложения.
Нужно удалить.

2024-11-27 13:26 UTC, Ononan commented on Calculator/build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-aop'
Нужно стараться избегать присутствия неиспользуемых зависимостей.
В данном случае дальше по коду не видно использования `spring-boot-starter-aop`

2024-11-27 13:26 UTC, Ononan commented on Calculator/src/main/java/calculator/controller/CalculatorController.java
> +        log.debug("Request: POST /offers; body={}", loanStatementRequestDto);
При указании уровня логирования debug, запись `Request: POST /offers` будет дублироваться, что выглядит странным. Выглядит логичнее при уровне debug логировать сообщения вида 
`log.debug("Request body={}", loanStatementRequestDto);`
Просьба поправить везде.

2024-11-27 13:26 UTC, Ononan commented on Calculator/src/main/java/calculator/controller/CalculatorController.java
> +        log.debug("measuring the processing speed: {} ms.", end - start);
Зачем здесь лог скорости работы метода? Если требуется хранить или мониторить время выполнения метода, это делается другими способами(см. распределенную трасировку или метрики приложения)

2024-11-27 13:26 UTC, Ononan commented on Calculator/src/main/java/calculator/controller/ExceptionHandlerController.java
> +public class ExceptionHandlerController {
Это все таки не Controller а ExceptionHandler соответственно лучше его назвать `ControllerExceptionHandler`

2024-11-27 13:26 UTC, Ononan commented on Calculator/src/main/java/calculator/dto/EmailMessage.java
Не нужно отдавать на ревью закомментированный код.
Просьба поправить везде.

2024-11-27 13:26 UTC, Ononan commented on Calculator/src/main/java/calculator/dto/request/validation/MinAgeValidator.java
> +        return age >= MIN_AGE;
В аннотации было определено поле years, по которому логично проверять, а по итогу используется константа.
Статья с примером получение значение переданного в аннотацию https://www.bezkoder.com/spring-boot-custom-validation/

2024-11-27 13:26 UTC, Ononan commented on Calculator/src/main/java/calculator/exceptions/ScoringException.java
> +        super(DEFAULT_MESSAGE);
Плохая практика, пробрасывать константу в ошибке, усложняющая анализ причины отказа при скоринге. Нужно для каждого кейса отказа, пробрасывать явный текст ошибки.

2024-11-27 13:26 UTC, Ononan commented on Calculator/src/main/java/calculator/service/scoring/ScoringProvider.java
> +//
Такой мурос по возможности стоит убирать

2024-11-27 13:26 UTC, Ononan commented on Calculator/src/main/java/calculator/service/creditCalculator/AnnuityCreditCalculatorImpl.java
> +package calculator.service.creditCalculator;
package не должен содержат заглавных букв(см. https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html)

2024-11-27 13:26 UTC, Ononan commented on Calculator/src/main/java/calculator/service/CalculatorService.java
> +public class CalculatorService implements CalculatorServiceImpl {
Во всех интерфейсах и классах перепутано название, CalculatorServiceImpl должен называться класс реализующий интерфейс, поэтому в конце у него Impl(implements) а интерфейс уже должен называться CalculatorService.
Просьба везде исправить

2024-11-27 13:26 UTC, Ononan commented on app.log
Аналогично мусорный файл, требуется удалить

2024-11-27 13:26 UTC, Ononan commented on Calculator/src/main/java/calculator/CalculatorApplication.java
> +package calculator;
Плохая практика называть package без префиксов, в данном случае следует хотя бы на основе groupId указать `com.calculator`

2024-11-27 13:26 UTC, Ononan commented on Calculator/src/main/java/calculator/service/CalculatorService.java
> +        log.info("Calculation of loans");
В сервисных метода особого смысла логировать вход и выход нет с уровнем info, достаточно лога с debug

2024-11-27 13:26 UTC, Ononan commented on Calculator/src/main/java/calculator/controller/ExceptionHandlerController.java
> +                .status(HttpStatus.INTERNAL_SERVER_ERROR)
INTERNAL_SERVER_ERROR(500 код) означает непредвиденную ошибку на стороне сервера, в данном случае у нас сработало ожидаемое бизнес правило, поэтому имеет смысл возвращать какую-то из 4xx ошибок.

2024-12-03 09:59 UTC, Ononan requested changes

2024-12-03 09:59 UTC, Ononan commented on Calculator/src/main/java/com/calculator/service/scoring/ScoringProviderImpl.java
> +    private Map<String, Boolean> getStringBooleanMap(int filterCount, int combinationIndex) {
Название метода странное, то что возвращается map с string и boolean ни о чем не говорит, метод должен иметь название говорящее о сущности того что он возвращает

2024-12-03 09:59 UTC, Ononan commented on Calculator/src/main/java/com/calculator/controller/CalculatorController.java
> +                    content = { @Content(mediaType = MediaType.APPLICATION_JSON_VALUE, schema = @Schema(implementation = ErrorMessageDto.class)) })})
В обработку ошибок был добавлен новый статус HttpStatus.UNPROCESSABLE_ENTITY, а в описание контракта его не добавили

2024-12-03 09:59 UTC, Ononan commented on Calculator/src/main/java/com/calculator/service/scoring/ScoringProviderImpl.java
> +            boolean isActive = (combinationIndex / (int) Math.pow(2, i)) % 2 == 1;
Решение стало более читаемо, но все равно сама конструкция выглядит сложной, нужно отказаться от циклов в данном виде, по созданию всех комбинаций фильтров что и исключит эти сложные конструкции с формированием комбинаций фильтров. 
Более очевидным решением выглядит, объявить константу которая будет содержать все пары комбинаций полей isInsuranceEnabled и isSalaryClient и на основе этой константы, уже формировать LoanOffer прогоняя значения через ScoringLoanFilter.

2024-12-03 09:59 UTC, Ononan commented on Calculator/src/main/java/calculator/controller/CalculatorController.java
> +        log.debug("Request: POST /offers; body={}", loanStatementRequestDto);
Удалять уровень info с информацией о вызываемом методе не нужно было

2024-12-03 18:54 UTC, Postreen commented on Calculator/app.log
исправил

2024-12-03 18:54 UTC, Postreen commented on Calculator/build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-aop'
исправил

2024-12-03 19:11 UTC, Postreen commented on Calculator/src/main/java/calculator/controller/CalculatorController.java
> +        log.debug("Request: POST /offers; body={}", loanStatementRequestDto);
исправил

2024-12-03 19:11 UTC, Postreen commented on Calculator/src/main/java/calculator/controller/CalculatorController.java
> +        log.debug("measuring the processing speed: {} ms.", end - start);
исправил

2024-12-03 19:11 UTC, Postreen commented on Calculator/src/main/java/calculator/controller/ExceptionHandlerController.java
> +public class ExceptionHandlerController {
исправил

2024-12-03 19:11 UTC, Postreen commented on Calculator/src/main/java/calculator/service/CalculatorService.java
> +public class CalculatorService implements CalculatorServiceImpl {
исправил

2024-12-03 19:12 UTC, Postreen commented on app.log
исправлено

2024-12-03 19:12 UTC, Postreen commented on Calculator/src/main/java/calculator/CalculatorApplication.java
> +package calculator;
Исправлено

2024-12-03 19:13 UTC, Postreen commented on Calculator/src/main/java/calculator/service/CalculatorService.java
> +        log.info("Calculation of loans");
Исправлено

2024-12-03 19:14 UTC, Postreen commented on Calculator/src/main/java/calculator/controller/ExceptionHandlerController.java
> +                .status(HttpStatus.INTERNAL_SERVER_ERROR)
Исправлено

2024-12-03 19:18 UTC, Postreen commented on Calculator/src/main/java/com/calculator/service/scoring/ScoringProviderImpl.java
> +    private Map<String, Boolean> getStringBooleanMap(int filterCount, int combinationIndex) {
Исправлено

2024-12-03 19:21 UTC, Postreen commented on Calculator/src/main/java/com/calculator/controller/CalculatorController.java
> +                    content = { @Content(mediaType = MediaType.APPLICATION_JSON_VALUE, schema = @Schema(implementation = ErrorMessageDto.class)) })})
Исправлено

2024-12-04 17:21 UTC, Postreen commented on Calculator/src/main/java/com/calculator/service/scoring/ScoringProviderImpl.java
> +            boolean isActive = (combinationIndex / (int) Math.pow(2, i)) % 2 == 1;
Исправлено

2024-12-05 09:55 UTC, merged