Initial setup for the deal
Postreen/credit-bank pull request #2
Opened 2024-12-11 09:00 UTC by Postreen

2024-12-11 09:05 UTC, Postreen commented on Deal/src/main/java/com/deal/controller/DealRestController.java
> +//import com.deal.controller.annotations.CalculateCreditSwaggerDescription;
Убрано

2024-12-18 11:15 UTC, Ononan requested changes

2024-12-18 11:15 UTC, Ononan commented on Deal/src/main/java/com/deal/controller/DealRestController.java
> +//import com.deal.controller.annotations.CalculateCreditSwaggerDescription;
Наверное забыл коммит запушить, нужно убрать

2024-12-18 11:15 UTC, Ononan commented on Deal/src/main/java/com/deal/mapping/ClientMapperHelper.java
> +public class ClientMapperHelper {
Зачем нужен этот класс, чем он отличается от ClientMapper? Также в данном случае можно было воспользоваться mapstruc для маппинга через аннотацию @MappingTarget

2024-12-18 11:15 UTC, Ononan commented on Deal/src/main/java/com/deal/controller/DealRestController.java
> +        List<LoanOfferDto> loanOffers = service.getLoanOffers(loanStatement);
Не подсветил на MVP1, но желательно чтобы метод контроллера и метод сервиса имели одно название

2024-12-18 11:15 UTC, Ononan commented on Deal/src/main/java/com/deal/service/client/CalculatorFeignClient.java
> +public interface CalculatorFeignClient {
Почему использовался Feign, когда  в задании явно указано использовать RestClient?

2024-12-18 11:15 UTC, Ononan commented on Deal/src/main/java/com/deal/utils/Client.java
> +package com.deal.utils;
Почему сущности базы данных хранятся в директории utils? Нужно перенести в директорию entity

2024-12-18 11:15 UTC, Ononan commented on Deal/src/main/java/com/deal/utils/Client.java
> +    UUID clientId;
Почему модификатор доступа private не установлен?

2024-12-18 11:15 UTC, Ononan commented on Deal/src/test/java/com/deal/services/client/CalculatorFeignClientTests.java
> +public class CalculatorFeignClientTests {
Мусор нужно удалять

2024-12-18 11:15 UTC, Ononan commented on Deal/src/main/java/com/deal/service/DealServiceImpl.java
> +    private Statement findStatementById(String statementId) {
Нужно заменить на тип UUID чтобы избавиться от лишних преобразований

2024-12-18 11:15 UTC, Ononan commented on Deal/src/test/resources/application.yaml
> +    url: jdbc:postgresql://localhost:5432/deal_db
Если тесты зависят от внешней базы, то нужно убрать зависимость

2024-12-18 19:37 UTC, Postreen commented on Deal/src/main/java/com/deal/controller/DealRestController.java
> +//import com.deal.controller.annotations.CalculateCreditSwaggerDescription;
Исправлено

2024-12-18 19:44 UTC, Postreen commented on Deal/src/main/java/com/deal/utils/Client.java
> +    UUID clientId;
Исправлено

2024-12-18 19:45 UTC, Postreen commented on Deal/src/test/java/com/deal/services/client/CalculatorFeignClientTests.java
> +public class CalculatorFeignClientTests {
Исправлено

2024-12-18 19:46 UTC, Postreen commented on Deal/src/main/java/com/deal/service/DealServiceImpl.java
> +    private Statement findStatementById(String statementId) {
Исправлено

2024-12-20 12:12 UTC, Postreen commented on Deal/src/main/java/com/deal/mapping/ClientMapperHelper.java
> +public class ClientMapperHelper {
Исправлено

2024-12-20 12:13 UTC, Postreen commented on Deal/src/main/java/com/deal/service/client/CalculatorFeignClient.java
> +public interface CalculatorFeignClient {
Исправлено

2024-12-20 12:20 UTC, Postreen commented on Deal/src/main/java/com/deal/controller/DealRestController.java
> +        List<LoanOfferDto> loanOffers = service.getLoanOffers(loanStatement);
Исправлено

2024-12-20 12:25 UTC, Postreen commented on Deal/src/main/java/com/deal/utils/Client.java
> +package com.deal.utils;
Исправлено

2024-12-20 12:25 UTC, Postreen commented on Deal/src/test/resources/application.yaml
> +    url: jdbc:postgresql://localhost:5432/deal_db
Исправлно

2024-12-23 12:49 UTC, Ononan requested changes

2024-12-23 12:49 UTC, Ononan commented on Deal/src/main/resources/application.yaml
> +    change-log: classpath:db.changelog/master.xml
Не нужно было в этот PR добавлять изменения из MVP3, они должны были идти отдельной веткой

2024-12-23 12:49 UTC, Ononan commented on Deal/src/main/java/com/deal/service/client/CalculatorRestClient.java
> +        this.restClient = RestClient.builder()
Зависимости подобно RestClient должны быть созданы как отдельные бины, чтобы ими управлял spring, и уменьшить связность логики клиента от конфигурирования RestClient.
В данном случае создание RestClient должно происходить в классе RestConfig в отдельном патеке config, где будет создан нужный бин, и его уже просто требуется внедрить в нужный сервис. см. [@Configuration](https://docs.spring.io/spring-framework/reference/core/beans/java/configuration-annotation.html)

2024-12-23 12:49 UTC, Ononan commented on Deal/src/main/java/com/deal/utils/json/Employment.java
> +package com.deal.utils.json;
классы Employment и т.д из патека json, также относятся к entity, поэтому их также следовало перенести

2024-12-25 12:11 UTC, merged