Feature/statement
Postreen/credit-bank pull request #4
Opened 2024-12-24 18:57 UTC by Postreen

Creating a statement service (MVP3)

2024-12-26 11:03 UTC, Ononan requested changes

2024-12-26 11:03 UTC, Ononan commented on Statement/src/main/java/com/statement/exceptions/PrescoringException.java
> +    private Set<ConstraintViolation<LoanStatementRequestDto>> resultPrescoring;
Не используемая переменная, нужно удалить, или как-то использовать

2024-12-26 11:03 UTC, Ononan commented on Statement/src/main/java/com/statement/service/StatementService.java
> +    List<LoanOfferDto> calculateLoanOffers(@Valid LoanStatementRequestDto loanStatement);
Зачем здесь @Valid?

2024-12-26 11:03 UTC, Ononan commented on Statement/src/main/java/com/statement/service/client/DealRestClient.java
> +        this.restClient = RestClient.builder()
Аналогично с MVP2 нужно убрать в отдельный класс config

2024-12-28 18:28 UTC, Postreen commented on Statement/src/main/java/com/statement/exceptions/PrescoringException.java
> +    private Set<ConstraintViolation<LoanStatementRequestDto>> resultPrescoring;
Исправлено

2024-12-28 18:28 UTC, Postreen commented on Statement/src/main/java/com/statement/service/StatementService.java
> +    List<LoanOfferDto> calculateLoanOffers(@Valid LoanStatementRequestDto loanStatement);
Исправлено

2024-12-28 18:28 UTC, Postreen commented on Statement/src/main/java/com/statement/service/client/DealRestClient.java
> +        this.restClient = RestClient.builder()
Исправлено

2025-01-09 11:54 UTC, Ononan approved these changes

2025-01-09 15:00 UTC, merged